logitechmediaserver:
  container_name: "logitechmediaserver"
  image: michaelmucciarone/logitechmediaserver
  restart: unless-stopped
  labels:
    - "autoheal=true"                # See https://github.com/willfarrell/docker-autoheal
    - "autoheal.stop.timeout=20"
  ports:
    - 9000:9000
    - 9005:9005
    - 9010:9010
    - 9090:9090
    - 3483:3483
    - 3483:3483/udp
    # - 5353:5353/udp                  # mDNS, watch for clash with avahi daemon on host
  volumes:
    - /volume1/Music:/mnt/music:ro
    - /volume1/Music/playlists:/mnt/playlists
    - /home/michael/lms-state:/mnt/state
